name: 'PR: Validate, Test and Danger'

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    name: âœ… Validate project
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸŸ¢ Setup NodeJS
        uses: actions/setup-node@v2

      - name: ğŸ“¥ Install dependencies
        run: yarn

      - name: ğŸ–ï¸ Check types
        run: yarn check:types

      - name: ğŸ’… Check format
        run: yarn check:format

      - name: ğŸ“‘ Check lint
        run: yarn check:lint

      - name: ğŸ”¤ Check spelling
        run: yarn check:spelling

  test:
    name: ğŸ§‘â€ğŸ”¬ Test project
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸŸ¢ Setup NodeJS
        uses: actions/setup-node@v2

      - name: ğŸ“¥ Install dependencies
        run: yarn

      - name: ğŸ§ª Run the tests
        run: yarn test:coverage

      - name: ğŸ“Š Generate coverage report
        uses: hrgui/lcov-reporter-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  danger:
    name: ğŸ‘©ğŸ»â€ğŸ’» Danger
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸŸ¢ Setup NodeJS
        uses: actions/setup-node@v2

      - name: ğŸ“¥ Install dependencies
        run: yarn

      - name: ğŸ‘©ğŸ»â€ğŸ’» Run the danger
      - run: yarn danger ci
